import { useState, useEffect } from "react";
import { Copy, FileText, Check, Download, AlertCircle } from "lucide-react";
import { PatientData, Message } from "../types";
import { generateSummary } from "../services/api";

interface SummaryViewProps {
  patientData: PatientData | null;
  conversation: Message[];
}

export default function SummaryView({ patientData, conversation }: SummaryViewProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    async function loadSummary() {
      try {
        const text = await generateSummary(patientData, conversation);
        setSummary(text);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadSummary();
  }, [patientData, conversation]);

  const handleCopy = () => {
    if (summary) {
      navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-3xl font-bold tracking-tight">Clinical Summary</h2>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            disabled={!summary}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 transition-colors shadow-sm text-sm font-semibold"
          >
            {copied ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied" : "Copy to Clipboard"}
          </button>
          <button
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors shadow-sm text-sm font-semibold"
          >
            <Download className="h-4 w-4" />
            Save as PDF
          </button>
        </div>
      </div>

      {loading ? (
        <div className="bg-white rounded-3xl p-12 shadow-sm ring-1 ring-slate-200 flex flex-col items-center justify-center space-y-4">
          <div className="relative">
            <div className="h-12 w-12 border-4 border-blue-100 border-t-blue-600 rounded-full animate-spin" />
            <FileText className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-5 w-5 text-blue-600" />
          </div>
          <p className="font-medium text-slate-500">Compiling visit data and generating summary...</p>
        </div>
      ) : summary ? (
        <div className="bg-white rounded-3xl p-8 shadow-sm ring-1 ring-slate-200">
          <div className="prose prose-slate max-w-none">
            <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-slate-700 bg-slate-50 p-6 rounded-2xl border border-slate-100">
              {summary}
            </pre>
          </div>
          
          <div className="mt-8 p-4 bg-emerald-50 rounded-2xl border border-emerald-100 flex gap-3 text-sm text-emerald-800">
            <AlertCircle className="h-5 w-5 shrink-0" />
            <p>
              This summary was generated by Language Doctor AI and verified against conversation context. 
              <strong> Review for clinical accuracy before entering into official EMR.</strong>
            </p>
          </div>
        </div>
      ) : (
        <div className="bg-red-50 text-red-600 p-6 rounded-2xl border border-red-100 font-medium">
          Failed to generate summary. Please try again.
        </div>
      )}
    </div>
  );
}
